# Settings for the Makefile which define
# various things like the names, paths, etc pp
#

# GRF Name
REPO_NAME        = OpenMSX
FILENAME         = openmsx
REPO_SHORTNAME   = OMSX
REPO_NIGHTLYNAME = nightly
REPO_ORIGIN      = default = Please download from original source.

REPO_FILENAME      = openmsx.obm
LICENSE_FILENAME   = docs/license.ptxt
CHANGELOG_FILENAME = docs/changelog.ptxt
README_FILENAME    = docs/readme.ptxt
DESC_FILENAME      = docs/descriptions.ptxt
LIST_FILENAME      = src/themes.list

# Build parameters and programmes
# Usually this needs no change.
TAR_FLAGS      = cf
ZIP_FLAGS      = -r
BZIP_FLAGS     = -k9f

# Macs have a different md5 command than linux or mingw envirnoment:
ifeq ($(OSTYPE),Darwin)
MD5SUM   = md5 -r
else
MD5SUM   = md5sum
endif

TAR      = tar
ZIP      = zip
BZIP     = bzip2
MAKE     = make
UNIX2DOS = unix2dos


TAR_SUFFIX   = tar
ZIP_SUFFIX   = zip
BZIP2_SUFFIX = bz2
TXT_SUFFIX   = txt
PTXT_SUFFIX  = ptxt

# Paths defining the directory layout
SRCDIR    = src
DOCDIR    = docs
SCRIPTDIR = scripts

MAINDIRS       = $(SRCDIR) $(DOCDIR) $(SCRIPTDIR)

# Define Replacement strings in the documentation
REPO_TITLE_DUMMY     = {{REPO_TITLE}}
REPO_FILENAME_DUMMY  = {{REPO_FILENAME}}
REPO_REVISION_DUMMY  = {{REPO_REVISION}}


REPO_TITLE    = $(REPO_NAME) $(VERSION_STRING)
TAR_FILENAME  = $(DIR_NAME).$(TAR_SUFFIX)
BZIP_FILENAME = $(TAR_FILENAME).$(BZIP2_SUFFIX)
ZIP_FILENAME  = $(DIR_NAME).$(ZIP_SUFFIX)
DOC_FILENAMES := $(addsuffix .$(TXT_SUFFIX),$(basename $(LICENSE_FILENAME) $(CHANGELOG_FILENAME) $(README_FILENAME)))
REV_FILENAME  = REV

BUNDLE_FILES  = $(DOC_FILENAMES) $(REPO_FILENAME)

# Remove the @ when you want a more verbose output.
_V := @
_E := @echo
