# This file defines the principal settings for this project

REPO_NAME          := OpenMSX
REPO_SHORTNAME     := OMSX
REPO_ORIGIN         = default = Please redownload from BaNaNaS.
# GRF_ID           :=

GENERATE_GRF       := music

BASE_FILENAME      := openmsx
THEMES_FILE        := src/themes.list
MIDI_FILES         := $(shell cat $(THEMES_FILE) | ./scripts/midifiles.py)
LANG_FILES         := $(shell ls lang/*.lng)
BUNDLE_FILES        = $(BASE_FILENAME).obm $(DOC_FILES) $(MIDI_FILES)

MD5_SRC_FILENAME   := $(BASE_FILENAME).obm
# If everything is default, you don't need the rest:

# comment out those dirs which are not in use
SCRIPT_DIR         = scripts
